### PR TITLE
Laplacian maxmode fix

### LINKED ISSUE #589: Laplacian maxmode limits
Looking through some of the Laplacian solvers I noticed a few possible issues/inefficiencies.

* Shoot_laplace seems to use loop limits that are up to but not including `maxmode`, whilst other solvers are up to and including `maxmode`.
* The following impls solve for all mode numbers, not just those `<=maxmode`; serial_tri, serial_band

### PR DESCRIPTION
**Pull request by d7919**
Closes #589 

* Ensure serial Laplacian methods skip modes greater than specified `maxmode`.
* Disallow use of `type=shoot` for standard Laplacian by throwing in the constructor.

### CODE REVIEW

File: src/invert/laplace/impls/serial_band/serial_band.cxx [hunk 1]
```diff
@@ -106,21 +106,19 @@ const FieldPerp LaplaceSerialBand::solve(const FieldPerp &b, const FieldPerp &x0
     xend = mesh->LocalNx-2;
   }
 
-  for(int iz=0;iz<=ncz/2;iz++) {
+  for(int iz=0;iz<=maxmode;iz++) {
```
Comment (bendudson) [inline src/invert/laplace/impls/serial_band/serial_band.cxx]: Is the value of the mode the result (xk1d?) set to zero anywhere for iz>maxmode?

Comment (d7919) [inline src/invert/laplace/impls/serial_band/serial_band.cxx]: That's a good point, it's not (not in `serial_tri` either) -- presumably something like

~~~~~
  for(int kz=maxmode+1; kz < ncz/2 + 1; kz++){
    for (int ix=0; ix<=ncx; ix++){
      xk[ix][kz] = 0.0;
    }
  }
~~~~~

after this loop would be an appropriate fix? 

Alternatively, we could do the initialisation at the point where we allocate the storage (i.e. in the constructor) such that this is only done once.
