### PR TITLE
Fixes for tokamak-2fluid example

### LINKED ISSUE #2041: BOUT++-v4.3.1 some examples can not run
Hello,

In BOUT++-v4.3.1 examples, uedge-benchmark and tokamak-2fluid can be compiled successfully, but Error encountered when running, errors are shown below:

Error encountered
====== Exception path ======
[bt] #8 ./ue_bmark() [0x439e3a]
_start 于 ??:?
[bt] #7 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7fc9e07a1a87]
__libc_start_main 于 /build/glibc-kAz5Pl/glibc-2.27/csu/../csu/libc-start.c:344
[bt] #6 ./ue_bmark() [0x433c35]
main 于 /home/huwanpeng/opt-gcc/gcc/include/c++/8.1.0/bits/unique_ptr.h:81
(已内连入)?? 于 /home/huwanpeng/opt-gcc/gcc/include/c++/8.1.0/bits/unique_ptr.h:274
(已内连入)main 于 /home/huwanpeng/codes/BOUT++-v4.3.1/examples/uedge-benchmark/ue_bmark.cxx:253
[bt] #5 ./ue_bmark() [0x474510]
Solver::solve(int, double) 于 /home/huwanpeng/codes/BOUT++-v4.3.1/src/solver/solver.cxx:476
[bt] #4 ./ue_bmark() [0x472905]
Solver::run_rhs(double) 于 /home/huwanpeng/codes/BOUT++-v4.3.1/src/solver/solver.cxx:1161
[bt] #3 ./ue_bmark() [0x44040f]
UedgeBenchmark::rhs(double) 于 /home/huwanpeng/codes/BOUT++-v4.3.1/examples/uedge-benchmark/ue_bmark.cxx:240 (discriminator 5)
[bt] #2 ./ue_bmark() [0x4bea74]
Div_par_K_Grad_par(Field3D const&, Field3D const&, CELL_LOC) 于 /home/huwanpeng/codes/BOUT++-v4.3.1/src/mesh/difops.cxx:308 (discriminator 18)
[bt] #1 ./ue_bmark() [0x4c1933]
Field3D const interp_to<Field3D>(Field3D const&, CELL_LOC, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) 于 /home/huwanpeng/codes/BOUT++-v4.3.1/src/mesh/../../include/interpolation.hxx:66 (discriminator 3)
====== Back trace ======
 -> Ncxx4::close on line 266 of 'ncxx4.cxx'
 -> const T interp_to(const T&, CELL_LOC, std::__cxx11::string) [with T = Field3D; std::__cxx11::string = std::__cxx11::basic_stri

====== Exception thrown ======
Assertion failed in ../../include/interpolation.hxx, line 66: loc != CELL_DEFAULT

Thanks, looking forward to reply.

### PR DESCRIPTION
**Pull request by johnomotani**
There were several staggered-grid issues with `examples/tokamak-2fluid` that I've started trying to fix here.

Should fix #2041

### CODE REVIEW

**Comment by johnomotani** [comment]
The run gets further for me now, but (configured with `--enable-debug`) I'm getting an out-of-bounds error from within `Div_par`. I don't know why, but it's using the `C4` method, which I don't normally use. I'm giving up for now, so if someone wants to take a look at this please do! The latest error message is
```
====== Exception path ======
[bt] #25 ./2fluid() [0x40ea59]
_start at ??:?
[bt] #24 /lib64/libc.so.6(__libc_start_main+0xf5) [0x2b8babca2b15]
__libc_start_main at ??:?
[bt] #23 ./2fluid() [0x40ed3f]
main at /marconi_work/FUA34_SOLBOUT4/jomotani/BOUT-next-clean/examples/tokamak-2fluid/2fluid.cxx:919 (discriminator 17)
[bt] #22 ./2fluid() [0x457892]
Solver::solve(int, double) at /marconi_work/FUA34_SOLBOUT4/jomotani/BOUT-next-clean/src/solver/solver.cxx:476
[bt] #21 ./2fluid() [0x45b2bb]
Solver::run_rhs(double) at /marconi_work/FUA34_SOLBOUT4/jomotani/BOUT-next-clean/src/solver/solver.cxx:1158
[bt] #20 ./2fluid() [0x446b29]
PhysicsModel::runRHS(double) at /marconi_work/FUA34_SOLBOUT4/jomotani/BOUT-next-clean/src/physics/physicsmodel.cxx:45
[bt] #19 ./2fluid() [0x41b3fc]
TwoFluid::rhs(double) at /marconi_work/FUA34_SOLBOUT4/jomotani/BOUT-next-clean/examples/tokamak-2fluid/2fluid.cxx:830 (discriminator 1)
[bt] #18 ./2fluid() [0x41075b]
Div_par_LtoC(Field3D const&) at /marconi_work/FUA34_SOLBOUT4/jomotani/BOUT-next-clean/examples/tokamak-2fluid/../../include/difops.hxx:268
[bt] #17 ./2fluid() [0x7d4dc2]
Div_par(Field3D const&, CELL_LOC, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) at /marconi_work/FUA34_SOLBOUT4/jomotani/BOUT-next-clean/src/mesh/difops.cxx:197
[bt] #16 ./2fluid() [0x55c84e]
Coordinates::Div_par(Field3D const&, CELL_LOC, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) at /marconi_work/FUA34_SOLBOUT4/jomotani/BOUT-next-clean/src/mesh/coordinates.cxx:1312 (discriminator 1)
[bt] #15 ./2fluid() [0x55bd28]
Coordinates::Grad_par(Field3D const&, CELL_LOC, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) at /marconi_work/FUA34_SOLBOUT4/jomotani/BOUT-next-clean/src/mesh/coordinates.cxx:1258 (discriminator 8)
[bt] #14 ./2fluid() [0x50cd45]
DDY(Field3D const&, CELL_LOC, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) at /marconi_work/FUA34_SOLBOUT4/jomotani/BOUT-next-clean/src/sys/derivs.cxx:88
[bt] #13 ./2fluid() [0x510b7a]
Field3D bout::derivatives::index::DDY<Field3D>(Field3D const&, CELL_LOC, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) at /marconi_work/FUA34_SOLBOUT4/jomotani/BOUT-next-clean/src/sys/../../include/bout/index_derivs_interface.hxx:206
[bt] #12 ./2fluid() [0x5144d4]
Field3D bout::derivatives::index::standardDerivative<Field3D, (DIRECTION)4, (DERIV)0>(Field3D const&, CELL_LOC, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) at /marconi_work/FUA34_SOLBOUT4/jomotani/BOUT-next-clean/src/sys/../../include/bout/index_derivs_interface.hxx:164
[bt] #11 ./2fluid() [0x5206b2]
std::function<void (Field3D const&, Field3D&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>::operator()(Field3D const&, Field3D&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const at /marconi/prod/opt/compilers/gnu/7.3.0/none/include/c++/7.3.0/bits/std_function.h:706
[bt] #10 ./2fluid() [0x6794f3]
std::_Function_handler<void (Field3D const&, Field3D&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), std::_Bind<void (DerivativeType<DDX_C4_stag>::*(DerivativeType<DDX_C4_stag>, std::_Placeholder<1>, std::_Placeholder<2>, std::_Placeholder<3>))(Field3D const&, Field3D&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const> >::_M_invoke(std::_Any_data const&, Field3D const&, Field3D&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) at /marconi/prod/opt/compilers/gnu/7.3.0/none/include/c++/7.3.0/bits/std_function.h:318
[bt] #9 ./2fluid() [0x6ea0ad]
void std::_Bind<void (DerivativeType<DDX_C4_stag>::*(DerivativeType<DDX_C4_stag>, std::_Placeholder<1>, std::_Placeholder<2>, std::_Placeholder<3>))(Field3D const&, Field3D&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const>::operator()<Field3D const&, Field3D&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void>(Field3D const&, Field3D&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) at /marconi/prod/opt/compilers/gnu/7.3.0/none/include/c++/7.3.0/functional:551
[bt] #8 ./2fluid() [0x7565d2]
void std::_Bind<void (DerivativeType<DDX_C4_stag>::*(DerivativeType<DDX_C4_stag>, std::_Placeholder<1>, std::_Placeholder<2>, std::_Placeholder<3>))(Field3D const&, Field3D&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const>::__call<void, Field3D const&, Field3D&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, 0ul, 1ul, 2ul, 3ul>(std::tuple<Field3D const&, Field3D&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>&&, std::_Index_tuple<0ul, 1ul, 2ul, 3ul>) at /marconi/prod/opt/compilers/gnu/7.3.0/none/include/c++/7.3.0/functional:469
[bt] #7 ./2fluid() [0x7a06bf]
std::__invoke_result<void (DerivativeType<DDX_C4_stag>::*&)(Field3D const&, Field3D&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const, DerivativeType<DDX_C4_stag>&, Field3D const&, Field3D&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>::type std::__invoke<void (DerivativeType<DDX_C4_stag>::*&)(Field3D const&, Field3D&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const, DerivativeType<DDX_C4_stag>&, Field3D const&, Field3D&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(void (DerivativeType<DDX_C4_stag>::*&)(Field3D const&, Field3D&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const, DerivativeType<DDX_C4_stag>&, Field3D const&, Field3D&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) at /marconi/prod/opt/compilers/gnu/7.3.0/none/include/c++/7.3.0/bits/invoke.h:95
[bt] #6 ./2fluid() [0x7c3db5]
void std::__invoke_impl<void, void (DerivativeType<DDX_C4_stag>::*&)(Field3D const&, Field3D&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const, DerivativeType<DDX_C4_stag>&, Field3D const&, Field3D&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(std::__invoke_memfun_ref, void (DerivativeType<DDX_C4_stag>::*&)(Field3D const&, Field3D&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const, DerivativeType<DDX_C4_stag>&, Field3D const&, Field3D&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) at /marconi/prod/opt/compilers/gnu/7.3.0/none/include/c++/7.3.0/bits/invoke.h:66 (discriminator 4)
[bt] #5 ./2fluid() [0x758dbb]
void DerivativeType<DDX_C4_stag>::standard<(DIRECTION)4, (STAGGER)2, 2, Field3D>(Field3D const&, Field3D&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const at /marconi_work/FUA34_SOLBOUT4/jomotani/BOUT-next-clean/src/mesh/../../include/bout/index_derivs.hxx:93 (discriminator 1)
[bt] #4 ./2fluid() [0x79d475]
stencil populateStencil<(DIRECTION)4, (STAGGER)2, 2, Field3D>(Field3D const&, Field3D::ind_type) at /marconi_work/FUA34_SOLBOUT4/jomotani/BOUT-next-clean/src/mesh/../../include/stencils.hxx:125
[bt] #3 ./2fluid() [0x7c2b8b]
void populateStencil<(DIRECTION)4, (STAGGER)2, 2, Field3D>(stencil&, Field3D const&, Field3D::ind_type) at /marconi_work/FUA34_SOLBOUT4/jomotani/BOUT-next-clean/src/mesh/../../include/stencils.hxx:111
[bt] #2 ./2fluid() [0x40fc0d]
Field3D::operator[](SpecificInd<(IND_TYPE)0> const&) const at /marconi_work/FUA34_SOLBOUT4/jomotani/BOUT-next-clean/examples/tokamak-2fluid/../../include/field3d.hxx:337
[bt] #1 ./2fluid() [0x41e45e]
Array<double, ArrayData<double> >::operator[](int) const at /marconi_work/FUA34_SOLBOUT4/jomotani/BOUT-next-clean/examples/tokamak-2fluid/../../include/bout/array.hxx:272 (discriminator 9)
====== Back trace ======
 -> Ncxx4::close on line 266 of 'ncxx4.cxx'
 -> void DerivativeType<FF>::standard(const T&, T&, const string&) const [with DIRECTION direction = (DIRECTION)4; STAGGER stagger
 -> T bout::derivatives::index::standardDerivative(const T&, CELL_LOC, const string&, const string&) [with T = Field3D; DIRECTION 
 -> T bout::derivatives::index::DDY(const T&, CELL_LOC, const string&, const string&) [with T = Field3D; std::__cxx11::string = st
 -> Coordinates::Grad_par( Field3D ) on line 1255 of 'coordinates.cxx'
 -> Coordinates::Div_par( Field3D ) on line 1294 of 'coordinates.cxx'
 -> Vorticity equation on line 800 of '2fluid.cxx'

====== Exception thrown ======
Assertion failed in ../../include/bout/array.hxx, line 272: 0 <= ind && ind < size()
```

File: examples/tokamak-2fluid/2fluid.cxx [hunk 1]
```diff
@@ -808,9 +827,9 @@ class TwoFluid : public PhysicsModel {
       
       if (rho_jpar1) {
         if (stagger) {
-          ddt(rho) += SQ(coord->Bxy)*Div_par_CtoL(jpar);
+          ddt(rho) += SQ(coord->Bxy)*Div_par_LtoC(jpar);
         } else  {
-          ddt(rho) += SQ(coord->Bxy)*Div_par(jpar, CELL_CENTRE);
+          ddt(rho) += SQ(coord->Bxy)*Div_par(jpar);
```
Comment (ZedThree) [inline examples/tokamak-2fluid/2fluid.cxx:832]: I think this is always correct here (and the similar constructions above and below)?
```cpp
          ddt(rho) += SQ(coord->Bxy)*Div_par(jpar, CELL_CENTRE);
```

Comment (johnomotani) [reply examples/tokamak-2fluid/2fluid.cxx:832]: It is, and I think we've updated to something like this without the conditionals in `next`. The reason I changed like this was because with the style it's written in, if `stagger = false` then no locations should need to be set (and the `stagger = true` branch is using the `Div_par_LtoC` form). I have no strong opinion on this though, so revert if you like. If I try really hard to justify the change, one could argue that if `stagger = false` then `jpar` should be at `CELL_CENTRE` (and if not it is an error) so putting the `CELL_CENTRE` argument in the `stagger = false` branch could potentially, conceivably, maybe hide an 'error' - I really don't think that's a good reason to have made this change though!

**Comment by johnomotani** [comment]
I tried back-porting the updates to `tokamak-2fluid` from `next` (where we got rid of all the `CtoL` operators) on `tokamak-2fluid-fix2` https://github.com/boutproject/BOUT-dev/tree/tokamak-2fluid-fix2, but I end up with the same error.

Also get the same error on `next` (after cherry-picking a couple more staggered-grid fixes) on `tokamak-2fluid-fix-next`, which is a bit worrying...

**Comment by ZedThree** [comment]
Urgh, that's probably not good!

As a side note, I've seen this in the backtraces from a few reported errors recently:

>  -> Ncxx4::close on line 266 of 'ncxx4.cxx'

I don't understand what it's doing in there!

**Review by ZedThree — APPROVED** [review]

**Review by ZedThree — APPROVED** [review]
