### PR TITLE
Fix for compiling without FFTW

### LINKED ISSUE #2370: compling without FFTW is broken
Either with `./configure --without-fftw` or `cmake -DBOUT_USE_FFTW=OFF`
```
fft_fftw.cxx: In function ‘unsigned int bout::fft::get_measurement_flag(FFT_MEASUREMENT_FLAG)’:
fft_fftw.cxx:74:14: error: ‘FFTW_ESTIMATE’ was not declared in this scope
   74 |       return FFTW_ESTIMATE;
      |              ^~~~~~~~~~~~~
fft_fftw.cxx:76:14: error: ‘FFTW_MEASURE’ was not declared in this scope
   76 |       return FFTW_MEASURE;
      |              ^~~~~~~~~~~~
fft_fftw.cxx:78:14: error: ‘FFTW_EXHAUSTIVE’ was not declared in this scope
   78 |       return FFTW_EXHAUSTIVE;
      |              ^~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by ZedThree**
Guard use of FFTW constants

Fixes #2370

### CODE REVIEW

File: src/invert/fft_fftw.cxx [hunk 1]
```diff
@@ -68,6 +68,7 @@ void fft_init(Options* options) {
   fft_init(fft_measurement_flag);
 }
 
+#if BOUT_HAS_FFTW
```
Comment (dschwoerer) [inline src/invert/fft_fftw.cxx:71]: Should we put only the function body in the `#if` to have a stabile ABI?

Comment (ZedThree) [reply src/invert/fft_fftw.cxx:71]: This function is only used internally, so it should really be in an anonymous namespace. Let me fix that now too.

**Review by dschwoerer — APPROVED** [review]
LGTM
