### PR TITLE
Fix MAYBE_UNUSED for some compilers

### LINKED ISSUE #1407: MAYBE_UNUSED causes compiling failure
In the definition of `MAYBE_UNUSED`, if `__has_cpp_attribute` is defined but `__has_cpp_attribute(maybe_unused)` is not, then `MAYBE_UNUSED` is not defined and causes compililation failures.
https://github.com/boutproject/BOUT-dev/blob/13fda6d569486bfda4c100c8547391ade2a15ee8/include/unused.hxx#L43-L51

### PR DESCRIPTION
**Pull request by ZedThree**
Some compilers may have `__has_cpp_attribute` but not
`maybe_unused`. Make sure MAYBE_UNUSED always gets defined to
something

Fixes #1407

### CODE REVIEW

File: include/unused.hxx [hunk 1]
```diff
@@ -44,10 +44,13 @@
 #if __has_cpp_attribute(maybe_unused)
 # define MAYBE_UNUSED(x) [[maybe_unused]] x
 #endif
-#elif defined(__GNUC__)
+#endif
+#ifndef MAYBE_UNUSED
+#if defined(__GNUC__)
 # define MAYBE_UNUSED(x) x __attribute__((unused))
```
Comment (d7919) [inline include/unused.hxx]: This could be `[[gnu::unused]] x` to make it look more like the maybe_unused branch above? This might also allow all the `MAYBE_UNUSED` calls to not take an argument (not sure if this is desirable).
