### PR TITLE
Fix BoutMesh boundary regions

### LINKED ISSUE #1656: Possible bug in Boutmesh::addBoundaryRegions?
Am I being dim, or should the y-indices be `yend, LocalNy - 1`? All the `RGN*_UPPER_Y` regions are similar -- copy-paste error?

https://github.com/boutproject/BOUT-dev/blob/1c8d7699c096a98dd28af393bd1ac32e4ffec6af/src/mesh/impls/bout/boutmesh.cxx#L2219-L2222

I think these are only important if the boundaries are evolved, and I guess we don't do that very often

### PR DESCRIPTION
**Pull request by ZedThree**
Fixes #1656 

One feature for v5.0 is to be able to properly mock-out MPI with `BoutComm` to make things like this easier to test. Otherwise it needs to run on several processes to properly test.

### CODE REVIEW

File: src/mesh/impls/bout/boutmesh.cxx [hunk 1]
```diff
@@ -2210,9 +2210,9 @@ void BoutMesh::addBoundaryRegions() {
   if (xe > xend)
     xe = xend;
 
-  addRegion3D("RGN_LOWER_Y", Region<Ind3D>(xs, xe, 0, ystart-1, 0, LocalNz-1,
+  addRegion3D("RGN_LOWER_Y", Region<Ind3D>(xs, xe, yend, LocalNy-1, 0, LocalNz-1,
```
Comment (johnomotani) [inline src/mesh/impls/bout/boutmesh.cxx]: I think `LOWER_Y` still be `0, ystart-1`.

Should be here that gets changed to `yend+1, LocalNy-1`:
https://github.com/boutproject/BOUT-dev/blob/58fc47aa98554f60d714b6391ffad56d3045727b/src/mesh/impls/bout/boutmesh.cxx#L2285-L2288

File: src/mesh/impls/bout/boutmesh.cxx [hunk 2]
```diff
@@ -2210,9 +2210,9 @@ void BoutMesh::addBoundaryRegions() {
...
                                            LocalNy, LocalNz, maxregionblocksize));
-  addRegion2D("RGN_LOWER_Y", Region<Ind2D>(xs, xe, 0, ystart-1, 0, 0,
+  addRegion2D("RGN_LOWER_Y", Region<Ind2D>(xs, xe, yend, LocalNy-1, 0, 0,
```
Comment (johnomotani) [inline src/mesh/impls/bout/boutmesh.cxx]: again `LOWER_Y` was correct before.

File: src/mesh/impls/bout/boutmesh.cxx [hunk 3]
```diff
@@ -2236,9 +2236,9 @@ void BoutMesh::addBoundaryRegions() {
     xe = -2;
   }
   
-  addRegion3D("RGN_UPPER_INNER_Y", Region<Ind3D>(xs, xe, 0, ystart-1, 0, LocalNz-1,
+  addRegion3D("RGN_UPPER_INNER_Y", Region<Ind3D>(xs, xe, yend, LocalNy-1, 0, LocalNz-1,
```
Comment (johnomotani) [inline src/mesh/impls/bout/boutmesh.cxx]: Shouldn't this be `yend+1, LocalNy-1`, so that the region only includes guard cells, and not the last column of grid cells?

File: src/mesh/impls/bout/boutmesh.cxx [hunk 4]
```diff
@@ -2236,9 +2236,9 @@ void BoutMesh::addBoundaryRegions() {
...
                                                  LocalNy, LocalNz, maxregionblocksize));
-  addRegion2D("RGN_UPPER_INNER_Y", Region<Ind2D>(xs, xe, 0, ystart-1, 0, 0,
+  addRegion2D("RGN_UPPER_INNER_Y", Region<Ind2D>(xs, xe, yend, LocalNy-1, 0, 0,
```
Comment (johnomotani) [inline src/mesh/impls/bout/boutmesh.cxx]: `yend+1`?

File: src/mesh/impls/bout/boutmesh.cxx [hunk 5]
```diff
@@ -2262,9 +2262,9 @@ void BoutMesh::addBoundaryRegions() {
       xe = xend;
   }
 
-  addRegion3D("RGN_UPPER_OUTER_Y", Region<Ind3D>(xs, xe, 0, ystart-1, 0, LocalNz-1,
+  addRegion3D("RGN_UPPER_OUTER_Y", Region<Ind3D>(xs, xe, yend, LocalNy-1, 0, LocalNz-1,
```
Comment (johnomotani) [inline src/mesh/impls/bout/boutmesh.cxx]: `yend+1`?

File: src/mesh/impls/bout/boutmesh.cxx [hunk 6]
```diff
@@ -2262,9 +2262,9 @@ void BoutMesh::addBoundaryRegions() {
...
                                                  LocalNy, LocalNz, maxregionblocksize));
-  addRegion2D("RGN_UPPER_OUTER_Y", Region<Ind2D>(xs, xe, 0, ystart-1, 0, 0,
+  addRegion2D("RGN_UPPER_OUTER_Y", Region<Ind2D>(xs, xe, yend, LocalNy-1, 0, 0,
```
Comment (johnomotani) [inline src/mesh/impls/bout/boutmesh.cxx]: `yend+1`?

File: src/mesh/impls/bout/boutmesh.cxx (hunk 1 above)
Comment (ZedThree) [reply src/mesh/impls/bout/boutmesh.cxx]: d'oh! Thanks! Too much very similar code!

File: src/mesh/impls/bout/boutmesh.cxx (hunk 3 above)
Comment (ZedThree) [reply src/mesh/impls/bout/boutmesh.cxx]: Ah yes, because `yend` is the last interior point, not one-past-the-end. Cheers!
